---
- name: создание сети
  community.docker.docker_network:
   name: "{{ network_name }}"
   driver: overlay

- name: выкладка сервисов
  include: "roles/deploy/services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
