---
rmq_defaults:
  - name: AMQP_EXCHANGE
    value: xchg_integrations
  - name: AMQP_USER
    value: "{{rmq.user}}"
  - name: AMQP_PASSWORD
    value: "{{rmq.password}}"
  - name: AMQP_HOSTNAME
    value: rmq



registry_name: "192.168.1.61:5000/" # местонахождение локального гегистра docker

services:
  - name: api
    version: latest
  # - name: app
  #   version: latest  
  # - name: converter
  #   version: latest
  - name: rmq
    version: latest

none_build_services:
  - name: rmq
    version: latest