galaxy_info:
  role_name: deploy
  description: выклвдка микросервисов на докер кластер
  author: vova
  license: vovas_corp
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
