---
- name: "[{{ name }}] конфигурация секрета"
  block:
    - name: "[{{ name }}] Создаем секрет"
      include: "roles/deploy/services/secretCreate.yml"


  rescue:
    - name: "[{{ name }}] Удаляем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent


    - name: "[{{ name }}] Пересоздаем секрет"
      include: "roles/deploy/services/secretCreate.yml"